modLoader="javafml"
loaderVersion="[35,)"
license="GNU GPL3"

[[mods]]
modId="wgvisualizer"
version="${file.jarVersion}"
displayName="Worldgen Visualizer"
authors="Tslat"
description='''
Live-tweak worldgen settings!

Enough of that pesky reloading and waiting stuff, that's so last century!
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
